export const projects = [
  {
    title: "Kayan X Fastrack",
    category: "Campaigns",
    image: "https://picsum.photos/seed/crocs/800/600",
    gallery: ["https://picsum.photos/seed/crocs1/800/600", "https://picsum.photos/seed/crocs2/800/600", "https://picsum.photos/seed/crocs3/800/600"],
    description: "To launch Fastrack's latest smart wearable, we merged high-concept futurism with sharp, street-ready fashion. The production focused on a high-speed rhythmic edit that mirrors the agility of the tech itself. We created a visual world, where sleek, futuristic elements meet fashion sensibilities, highlighting the watch as the centrepiece of a tech forward lifestyle.",
    tags: ["Content Production"],
    isBlog: false,
  },
  {
    title: "Bestseller X Rolling Loud",
    category: "Reels",
    image: "https://picsum.photos/seed/drip/800/600",
    gallery: ["https://picsum.photos/seed/drip1/800/600", "https://picsum.photos/seed/drip2/800/600"],
    description: "We captured the high-octane energy of the festival circuit to showcase the ultimate festive-wear collections for ONLY and Jack & Jones. By blending raw, rhythmic storytelling with street-style aesthetics, we produced a series of visuals that mirror the pulse of the global music scene. The result is a high-impact campaign designed to resonate with a trend-first audience on a global stage.",
    tags: ["Content Production", "Studio"],
    isBlog: false,
  },
  {
    title: "Drip Project - Launch Campaign",
    category: "UGC",
    image: "https://picsum.photos/seed/fastrack/800/600",
    gallery: [],
    description: "To launch #TheReckoningCollection, we moved away from traditional product displays to create a high-stakes, cinematic narrative. The production utilized sharp, rhythmic editing and aggressive lighting to mirror the bold evolution of the brand. It wasn't just a collection reveal; it was a visual statement of intent that set a new benchmark for the Drip Project aesthetic.",
    tags: ["SMM", "Content Production"],
    isBlog: true,
    blogUrl: "/blog/drip-project-launch",
  },
  {
    title: "Drip Project - Core Campaign",
    category: "Studio",
    image: "https://picsum.photos/seed/urban/800/600",
    gallery: ["https://picsum.photos/seed/urban1/800/600", "https://picsum.photos/seed/urban2/800/600"],
    description: "Precision meets lifestyle in this core jewellery campaign, where the focus was on capturing the intricate craftsmanship of each piece through a high-fashion lens. By balancing macro-detail shots with high-energy movement, we created a visual language that feels both premium and street-luxe, ensuring the product remains the undisputed hero of the frame.",
    tags: ["Studio", "Content Production"],
    isBlog: false,
  },
  {
    title: "Spotify Rap91 Aftermovie",
    category: "Campaigns",
    image: "https://picsum.photos/seed/nike/800/600",
    gallery: ["https://picsum.photos/seed/nike1/800/600", "https://picsum.photos/seed/nike2/800/600"],
    description: "We went ground-zero at the Spotify Rap91 showcase to capture the raw, unfiltered energy of the Indian hip-hop scene. This isn't just an aftermovie; it’s a high-octane visual recap that mirrors the rhythm and grit of the performances. By blending fast-paced handheld cinematography with stylized post-production, we translated the live atmosphere into a digital experience that keeps the movement loud.",
    tags: ["Content Production"],
    isBlog: false,
  },
  {
    title: "Drip Project - Men's Jewellery",
    category: "Reels",
    image: "https://picsum.photos/seed/redbull/800/600",
    gallery: ["https://picsum.photos/seed/redbull1/800/600", "https://picsum.photos/seed/redbull2/800/600"],
    description: "Taking the brand international, we shot in Thailand to produce a raw, high-octane campaign for the Men’s Jewellery line. This shoot leaned into tropical-noir aesthetics, utilizing the unique textures of the location to elevate the rugged yet refined nature of the collection. It’s a testament to our ability to execute seamless, high-end productions regardless of geography.",
    tags: ["SMM"],
    isBlog: false,
  },
  {
    title: "Birkenstock X Lakme Fashion Week",
    category: "Campaigns",
    image: "https://picsum.photos/seed/nykaa/800/600",
    gallery: ["https://picsum.photos/seed/nykaa1/800/600", "https://picsum.photos/seed/nykaa2/800/600"],
    description: "We took an iconic global heritage brand and placed it at the center of India’s premier fashion stage. For the Lakme Fashion Week Campaign, we focused on the intersection of high-fashion styling and timeless comfort, creating a visual narrative that felt both elevated and effortless. The accompanying Aftermovie captured the kinetic energy behind the scenes and on the runway, blending high-speed transitions with candid, stylistic frames. Together, these pieces served as a comprehensive digital record of the brand's presence, ensuring the momentum of the live event translated into a lasting, high-impact social experience.",
    tags: ["Production", "Beauty"],
    isBlog: false,
  },
];
